FROM alpine
RUN apk update
RUN apk upgrade
RUN apk add git
RUN apk add g++
RUN git clone https://github.com/p0l0satik/Client_server_graph.git
WORKDIR Client_server_graph
RUN g++ -o server server.cpp
CMD ./server
